// Arohi VetMitra - Feed Reference Database
// Based on CB_Jersey_NASEM_2021_Ration_Calculator.xlsx (Sheet 2: Feed Reference)
// Expanded with regional Indian dairy feedstuffs

import { FeedItem } from '../types';

export const NASEM_DEFAULT_FEEDS: FeedItem[] = [
  // 9 Core Feeds directly from the workbook
  {
    id: 'wheat_bran',
    name: 'Wheat bran',
    nameOdia: 'ଗହମ ଚୋକଡ଼ (Wheat Bran)',
    nameHindi: 'गेहूं चोकर (Wheat Bran)',
    category: 'concentrate',
    dmPercent: 89,
    cpPercent: 16.0,
    ndfPercent: 45.3,
    adfPercent: 14.5,
    caPercent: 0.12,
    pPercent: 0.84,
    mgPercent: 0.33,
    kPercent: 1.06,
  },
  {
    id: 'gnoc',
    name: 'Groundnut Oil Cake (GNOC)',
    nameOdia: 'ଚିନାବାଦାମ ପିଡ଼ିଆ (GNOC)',
    nameHindi: 'मूंगफली खल (GNOC)',
    category: 'concentrate',
    dmPercent: 91,
    cpPercent: 40.0,
    ndfPercent: 23.3,
    adfPercent: 18.2,
    caPercent: 0.20,
    pPercent: 0.60,
    mgPercent: 0.30,
    kPercent: 1.10,
  },
  {
    id: 'soya_doc',
    name: 'Soybean DOC (De-oiled cake)',
    nameOdia: 'ସୋୟାବିନ୍ ଡି.ଓ.ସି. (Soya DOC)',
    nameHindi: 'सोयाबीन डीओसी (Soya DOC)',
    category: 'concentrate',
    dmPercent: 89,
    cpPercent: 45.5,
    ndfPercent: 20.5,
    adfPercent: 8.8,
    caPercent: 0.30,
    pPercent: 0.65,
    mgPercent: 0.29,
    kPercent: 2.20,
  },
  {
    id: 'mung_chuni',
    name: 'Mung chuni',
    nameOdia: 'ମୁଗ ଚୁନି (Mung Chuni)',
    nameHindi: 'मूंग चूनी (Mung Chuni)',
    category: 'concentrate',
    dmPercent: 90,
    cpPercent: 22.0,
    ndfPercent: 42.0,
    adfPercent: 24.0,
    caPercent: 0.55,
    pPercent: 0.38,
    mgPercent: 0.34,
    kPercent: 1.10,
  },
  {
    id: 'biri_chuni',
    name: 'Biri / Urad chuni',
    nameOdia: 'ବିରି ଚୁନି (Urad/Biri Chuni)',
    nameHindi: 'उड़द चूनी (Urad Chuni)',
    category: 'concentrate',
    dmPercent: 90,
    cpPercent: 21.0,
    ndfPercent: 46.2,
    adfPercent: 27.0,
    caPercent: 0.50,
    pPercent: 0.40,
    mgPercent: 0.35,
    kPercent: 1.15,
  },
  {
    id: 'ground_maize',
    name: 'Ground maize grain',
    nameOdia: 'ମକା ଦାନା / ଚୂର୍ଣ୍ଣ (Ground Maize)',
    nameHindi: 'मक्का दाना (Ground Maize)',
    category: 'concentrate',
    dmPercent: 89,
    cpPercent: 9.0,
    ndfPercent: 15.6,
    adfPercent: 3.5,
    caPercent: 0.02,
    pPercent: 0.26,
    mgPercent: 0.10,
    kPercent: 0.37,
  },
  {
    id: 'dorb',
    name: 'De-Oiled Rice Bran (DORB)',
    nameOdia: 'ଡି.ଓ.ଆର୍.ବି. (DORB)',
    nameHindi: 'डीओआरबी (DORB)',
    category: 'concentrate',
    dmPercent: 90,
    cpPercent: 15.5,
    ndfPercent: 38.2,
    adfPercent: 11.9,
    caPercent: 0.15,
    pPercent: 1.20,
    mgPercent: 0.50,
    kPercent: 1.20,
  },
  {
    id: 'hybrid_napier',
    name: 'Hybrid Napier (Green Fodder)',
    nameOdia: 'ହାଇବ୍ରିଡ୍ ନେପିୟର ଘାସ (Hybrid Napier)',
    nameHindi: 'हाइब्रिड नेपियर हरा चारा',
    category: 'forage_green',
    dmPercent: 20,
    cpPercent: 12.5,
    ndfPercent: 66.4,
    adfPercent: 34.7,
    caPercent: 0.57,
    pPercent: 0.17,
    mgPercent: 0.41,
    kPercent: 0.95,
  },
  {
    id: 'paddy_straw',
    name: 'Paddy straw (Dry Roughage)',
    nameOdia: 'ଧାନ ନଡ଼ା (Paddy Straw)',
    nameHindi: 'धान का पुआल / पैरा (Paddy Straw)',
    category: 'forage_dry',
    dmPercent: 90,
    cpPercent: 4.1,
    ndfPercent: 68.4,
    adfPercent: 41.0,
    caPercent: 0.40,
    pPercent: 0.14,
    mgPercent: 0.12,
    kPercent: 0.74,
  },

  // Expanded Indian dairy & regional feedstuffs
  {
    id: 'maize_green',
    name: 'Green Maize Fodder',
    nameOdia: 'ସବୁଜ ମକା ଘାସ (Green Maize)',
    nameHindi: 'हरा मक्का चारा',
    category: 'forage_green',
    dmPercent: 22,
    cpPercent: 8.5,
    ndfPercent: 55.0,
    adfPercent: 31.0,
    caPercent: 0.38,
    pPercent: 0.22,
    mgPercent: 0.25,
    kPercent: 1.20,
  },
  {
    id: 'sorghum_green',
    name: 'Green Sorghum / Jowar Fodder',
    nameOdia: 'ସବୁଜ ଜୁଆର ଚାରା (Green Jowar)',
    nameHindi: 'हरा ज्वार चारा',
    category: 'forage_green',
    dmPercent: 25,
    cpPercent: 7.5,
    ndfPercent: 62.0,
    adfPercent: 36.0,
    caPercent: 0.42,
    pPercent: 0.20,
    mgPercent: 0.28,
    kPercent: 1.10,
  },
  {
    id: 'berseem_green',
    name: 'Berseem / Egyptian Clover',
    nameOdia: 'ବରସିମ୍ ଘାସ (Berseem)',
    nameHindi: 'बरसीम हरा चारा',
    category: 'forage_green',
    dmPercent: 15,
    cpPercent: 19.5,
    ndfPercent: 44.0,
    adfPercent: 28.0,
    caPercent: 1.40,
    pPercent: 0.28,
    mgPercent: 0.38,
    kPercent: 2.40,
  },
  {
    id: 'wheat_straw',
    name: 'Wheat straw / Bhusa',
    nameOdia: 'ଗହମ ଭୁଷା / ନଡ଼ା (Wheat Straw)',
    nameHindi: 'गेहूं का भूसा',
    category: 'forage_dry',
    dmPercent: 90,
    cpPercent: 3.5,
    ndfPercent: 72.0,
    adfPercent: 48.0,
    caPercent: 0.30,
    pPercent: 0.10,
    mgPercent: 0.12,
    kPercent: 1.10,
  },
  {
    id: 'mustard_cake',
    name: 'Mustard Oil Cake (MOC)',
    nameOdia: 'ସୋରିଷ ପିଡ଼ିଆ (Mustard Cake)',
    nameHindi: 'सरसों की खल (Mustard Cake)',
    category: 'concentrate',
    dmPercent: 90,
    cpPercent: 36.0,
    ndfPercent: 26.5,
    adfPercent: 17.0,
    caPercent: 0.65,
    pPercent: 1.10,
    mgPercent: 0.45,
    kPercent: 1.25,
  },
  {
    id: 'cottonseed_cake',
    name: 'Cottonseed Cake',
    nameOdia: 'କପା ମଞ୍ଜି ପିଡ଼ିଆ (Cottonseed Cake)',
    nameHindi: 'बिनौला खल (Cottonseed Cake)',
    category: 'concentrate',
    dmPercent: 90,
    cpPercent: 24.0,
    ndfPercent: 48.0,
    adfPercent: 32.0,
    caPercent: 0.25,
    pPercent: 0.70,
    mgPercent: 0.35,
    kPercent: 1.30,
  },
  {
    id: 'commercial_cattle_feed',
    name: 'Compound Cattle Feed / Pellet (Type 1)',
    nameOdia: 'ପ୍ରସ୍ତୁତ ଦାନା / ପେଲେଟ୍ (Compound Feed)',
    nameHindi: 'संतुलित पशु आहार / दाना (Cattle Feed)',
    category: 'concentrate',
    dmPercent: 90,
    cpPercent: 20.0,
    ndfPercent: 30.0,
    adfPercent: 15.0,
    caPercent: 0.80,
    pPercent: 0.50,
    mgPercent: 0.30,
    kPercent: 1.00,
  },
  {
    id: 'mineral_mixture',
    name: 'Area-Specific Mineral Mixture',
    nameOdia: 'ମିନେରାଲ୍ ମିକ୍ସଚର୍ (Mineral Mixture)',
    nameHindi: 'खनिज मिश्रण (Mineral Mixture)',
    category: 'mineral',
    dmPercent: 98,
    cpPercent: 0.0,
    ndfPercent: 0.0,
    adfPercent: 0.0,
    caPercent: 20.0,
    pPercent: 10.0,
    mgPercent: 5.0,
    kPercent: 0.0,
  },
  {
    id: 'common_salt',
    name: 'Common Salt (NaCl)',
    nameOdia: 'ସାଧାରଣ ଲୁଣ (Salt)',
    nameHindi: 'साधारण नमक (Salt)',
    category: 'mineral',
    dmPercent: 99,
    cpPercent: 0.0,
    ndfPercent: 0.0,
    adfPercent: 0.0,
    caPercent: 0.0,
    pPercent: 0.0,
    mgPercent: 0.0,
    kPercent: 0.0,
  },
  {
    id: 'calcite_powder',
    name: 'Calcite Powder / Limestone',
    nameOdia: 'ଚୂନ ପାଉଡର (Calcite Powder)',
    nameHindi: 'कैल्साइट पाउडर / चूना',
    category: 'mineral',
    dmPercent: 99,
    cpPercent: 0.0,
    ndfPercent: 0.0,
    adfPercent: 0.0,
    caPercent: 36.0,
    pPercent: 0.0,
    mgPercent: 0.5,
    kPercent: 0.0,
  },
  {
    id: 'dcp',
    name: 'Di-Calcium Phosphate (DCP)',
    nameOdia: 'ଡାଇ-କ୍ୟାଲସିୟମ୍ ଫସଫେଟ୍ (DCP)',
    nameHindi: 'डाई-कैल्शियम फॉस्फेट (DCP)',
    category: 'mineral',
    dmPercent: 98,
    cpPercent: 0.0,
    ndfPercent: 0.0,
    adfPercent: 0.0,
    caPercent: 24.0,
    pPercent: 18.0,
    mgPercent: 0.2,
    kPercent: 0.0,
  },
];
