import { Learning3DModel } from '../../types/learning3d';

export const LEARNING_3D_MODELS: Learning3DModel[] = [
  // 1. BIOLOGY - HUMAN HEART
  {
    id: 'human_heart',
    name: 'Human Heart',
    title: 'Anatomy & Physiology of the Human Heart',
    subject: 'biology',
    difficulty: 'high_school',
    tags: ['cardiology', 'circulatory system', 'cardiac cycle', 'blood flow', 'valves', 'anatomy', 'mbbs'],
    summary: 'Explore the 4-chambered muscular organ that pumps blood throughout the circulatory system.',
    overviewText: 'The human heart is a muscular pump responsible for circulating blood around the body. It consists of four main chambers (Right Atrium, Right Ventricle, Left Atrium, Left Ventricle) separated by cardiac valves that enforce one-way blood circulation.',
    meshType: 'procedural_heart',
    sketchfabEmbedId: 'f77dfce0fefb4b9f848c27944faae000',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'right_atrium',
        name: 'Right Atrium',
        label: 'Right Atrium (RA)',
        description: 'Receives deoxygenated blood returning from the body via the Superior and Inferior Vena Cava.',
        detailedExplanation: 'The Right Atrium is the upper right chamber. It collects oxygen-depleted venous blood and pumps it down into the Right Ventricle through the Tricuspid Valve during atrial systole.',
        functionText: 'Receives deoxygenated blood and regulates atrial filling pressure.',
        importanceText: 'Ensures venous blood from the head and systemic organs enters the heart continuously without backpressure.',
        color: '#3b82f6',
        highlightColor: '#60a5fa',
        position: [-0.9, 0.6, 0.2]
      },
      {
        id: 'tricuspid_valve',
        name: 'Tricuspid Valve',
        label: 'Tricuspid Valve',
        description: 'Atrioventricular valve with 3 cusps that prevents backflow into the Right Atrium.',
        detailedExplanation: 'Located between the Right Atrium and Right Ventricle. Held in place by chordae tendineae (heart strings) attached to papillary muscles. It snaps shut when the Right Ventricle contracts.',
        functionText: 'Prevents backward leakage of blood into the right atrium during ventricular contraction.',
        importanceText: 'Valvular incompetence causes tricuspid regurgitation, swelling, and peripheral edema.',
        color: '#6366f1',
        highlightColor: '#818cf8',
        position: [-0.4, 0.1, 0.3]
      },
      {
        id: 'right_ventricle',
        name: 'Right Ventricle',
        label: 'Right Ventricle (RV)',
        description: 'Pumps deoxygenated blood through the Pulmonary Valve into the lungs for re-oxygenation.',
        detailedExplanation: 'The Right Ventricle has a crescent-shaped lumen with a thinner muscular wall compared to the left ventricle because pulmonary vascular resistance is significantly lower than systemic arterial pressure.',
        functionText: 'Drives low-pressure pulmonary circulation to supply oxygen-depleted blood to pulmonary capillaries.',
        importanceText: 'Critical for respiratory gas exchange (CO2 removal and O2 uptake in lungs).',
        color: '#1d4ed8',
        highlightColor: '#3b82f6',
        position: [-0.7, -0.6, 0.4]
      },
      {
        id: 'left_atrium',
        name: 'Left Atrium',
        label: 'Left Atrium (LA)',
        description: 'Receives freshly oxygenated blood returning from the lungs via 4 Pulmonary Veins.',
        detailedExplanation: 'Situated on the upper left posterior aspect of the heart. Receives bright red, oxygen-rich blood from the left and right lungs.',
        functionText: 'Acts as a holding reservoir for oxygenated blood prior to left ventricular contraction.',
        importanceText: 'Atrial fibrillation in the LA is a common cause of embolic stroke.',
        color: '#ef4444',
        highlightColor: '#f87171',
        position: [0.8, 0.7, -0.2]
      },
      {
        id: 'mitral_valve',
        name: 'Mitral Valve (Bicuspid Valve)',
        label: 'Mitral Valve',
        description: 'Dual-cusp valve preventing regurgitation from Left Ventricle into Left Atrium.',
        detailedExplanation: 'Also called the Bicuspid Valve. Withstands high pressure generated by the left ventricle as it contracts to pump blood throughout the entire body.',
        functionText: 'Seals the left atrium shut during high-pressure left ventricular contraction.',
        importanceText: 'Mitral stenosis or prolapse causes shortness of breath and heart failure.',
        color: '#f43f5e',
        highlightColor: '#fb7185',
        position: [0.4, 0.1, 0.2]
      },
      {
        id: 'left_ventricle',
        name: 'Left Ventricle',
        label: 'Left Ventricle (LV)',
        description: 'Thickest muscular chamber; pumps oxygenated blood under high pressure into the Aorta.',
        detailedExplanation: 'The wall of the Left Ventricle is 3 times thicker than the Right Ventricle because it must overcome systemic vascular resistance to distribute blood to the brain, organs, and limbs.',
        functionText: 'Generates systolic blood pressure (120 mmHg) to power systemic blood circulation.',
        importanceText: 'Primary cardiac engine; hypertrophy occurs in chronic hypertension.',
        color: '#dc2626',
        highlightColor: '#ef4444',
        position: [0.6, -0.7, 0.2]
      },
      {
        id: 'aorta',
        name: 'Aorta & Aortic Arch',
        label: 'Aorta',
        description: 'The main trunk arterial vessel carrying oxygenated blood from the heart to the body.',
        detailedExplanation: 'Arises from the Left Ventricle via the Aortic Valve. Curves upward into the Aortic Arch, giving off branches (brachiocephalic, carotid, subclavian) to the head and arms, then descends into the chest and abdomen.',
        functionText: 'High-pressure distribution pipeline for oxygenated blood.',
        importanceText: 'Aortic aneurysm or dissection is a life-threatening medical emergency.',
        color: '#b91c1c',
        highlightColor: '#f87171',
        position: [0.2, 1.4, 0.0]
      },
      {
        id: 'pulmonary_artery',
        name: 'Pulmonary Artery Trunk',
        label: 'Pulmonary Artery',
        description: 'Carries deoxygenated blood from Right Ventricle to the left and right lungs.',
        detailedExplanation: 'The only artery in the adult body that carries oxygen-poor blood. Originates from the right ventricle and splits into right and left pulmonary arteries.',
        functionText: 'Transports venous blood to alveoli for gaseous exchange.',
        importanceText: 'Pulmonary embolism occurs when a blood clot blocks this artery.',
        color: '#2563eb',
        highlightColor: '#60a5fa',
        position: [-0.3, 1.1, -0.3]
      },
      {
        id: 'superior_vena_cava',
        name: 'Superior Vena Cava',
        label: 'Superior Vena Cava',
        description: 'Large vein returning deoxygenated blood from the head, neck, and upper limbs into the Right Atrium.',
        detailedExplanation: 'The Superior Vena Cava is a major venous channel draining systemic venous blood from the upper body directly into the upper posterior portion of the Right Atrium.',
        functionText: 'Drains venous blood from upper body into the heart.',
        importanceText: 'Obstruction leads to Superior Vena Cava Syndrome with facial edema and venous engorgement.',
        color: '#1e40af',
        highlightColor: '#3b82f6',
        position: [-0.8, 1.3, 0.1]
      },
      {
        id: 'inferior_vena_cava',
        name: 'Inferior Vena Cava',
        label: 'Inferior Vena Cava',
        description: 'Large vein bringing oxygen-depleted blood from the lower limbs and abdominal organs back to the heart.',
        detailedExplanation: 'The Inferior Vena Cava travels alongside the abdominal aorta, collecting venous return from abdominal viscera, kidneys, and legs before entering the lower Right Atrium.',
        functionText: 'Drains venous blood from lower body into right atrium.',
        importanceText: 'DVT and IVC thrombus can embolize into the pulmonary circulation.',
        color: '#1d4ed8',
        highlightColor: '#60a5fa',
        position: [-0.8, -1.3, -0.1]
      },
      {
        id: 'pulmonary_veins',
        name: 'Pulmonary Veins',
        label: 'Pulmonary Veins',
        description: 'Four pulmonary veins carrying oxygenated blood from the lungs into the Left Atrium.',
        detailedExplanation: 'The only veins in the human body that carry bright red, oxygenated blood. Two left and two right pulmonary veins drain directly into the posterior Left Atrium.',
        functionText: 'Transports oxygenated blood from pulmonary capillary beds to the left atrium.',
        importanceText: 'Pulmonary vein isolation is a key interventional procedure for atrial fibrillation.',
        color: '#f43f5e',
        highlightColor: '#fb7185',
        position: [0.7, 0.9, -0.4]
      },
      {
        id: 'myocardium',
        name: 'Myocardium',
        label: 'Myocardium',
        description: 'Muscular tissue layer of the heart that contracts rhythmically to pump blood.',
        detailedExplanation: 'Composed of specialized cardiac muscle fibers (cardiomyocytes) connected by intercalated discs with gap junctions, enabling coordinated involuntary contractions.',
        functionText: 'Generates contractile force to pump blood through pulmonary and systemic vascular beds.',
        importanceText: 'Myocardial infarction (heart attack) occurs when coronary blood flow to the myocardium is blocked.',
        color: '#991b1b',
        highlightColor: '#ef4444',
        position: [0.3, -1.1, 0.1]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'Overview & The Four Chambers',
        componentId: 'right_atrium',
        explanation: 'Welcome to the Human Heart lesson! The heart consists of 4 main chambers: Right Atrium, Right Ventricle, Left Atrium, and Left Ventricle.',
        detailedNotes: 'The right side handles deoxygenated blood from the body, while the left side handles oxygenated blood from the lungs.',
        cameraPosition: [0, 0, 5],
        cameraTarget: [0, 0, 0],
        audioNarrationText: 'Welcome to 3D Learning on Arohi AI. The human heart has four main chambers that continuously circulate blood through two distinct loops.'
      },
      {
        stepNumber: 2,
        title: 'Venous Return & Right Atrium',
        componentId: 'right_atrium',
        explanation: 'Oxygen-depleted blood returning from the head and body enters the Right Atrium.',
        detailedNotes: 'Pressure in the RA is low (~2-6 mmHg). As it fills, blood drains downward into the Right Ventricle.',
        cameraPosition: [-1.8, 1.2, 3],
        cameraTarget: [-0.9, 0.6, 0.2],
        audioNarrationText: 'Deoxygenated blood returns from the body and collects inside the Right Atrium.'
      },
      {
        stepNumber: 3,
        title: 'Tricuspid Valve Mechanism',
        componentId: 'tricuspid_valve',
        explanation: 'The Tricuspid Valve opens to let blood flow into the Right Ventricle, then closes tightly to prevent backflow.',
        detailedNotes: 'Three cusps are anchored by fibrous chordae tendineae. When the ventricle squeezes, these valves snap shut.',
        cameraPosition: [-0.8, 0.2, 2.5],
        cameraTarget: [-0.4, 0.1, 0.3],
        audioNarrationText: 'The Tricuspid Valve acts as a one-way doorway between the right atrium and right ventricle.'
      },
      {
        stepNumber: 4,
        title: 'Right Ventricle & Pulmonary Circulation',
        componentId: 'right_ventricle',
        explanation: 'The Right Ventricle contracts and forces blood through the Pulmonary Artery to the lungs.',
        detailedNotes: 'In the lungs, red blood cells release CO2 and absorb oxygen across alveolar membranes.',
        cameraPosition: [-1.4, -0.8, 3.2],
        cameraTarget: [-0.7, -0.6, 0.4],
        audioNarrationText: 'The Right Ventricle pumps blood to the lungs where carbon dioxide is exchanged for fresh oxygen.'
      },
      {
        stepNumber: 5,
        title: 'Pulmonary Artery Trunk',
        componentId: 'pulmonary_artery',
        explanation: 'Notice that the Pulmonary Artery carries deoxygenated blood — the only artery in adults with blue oxygen-poor blood.',
        detailedNotes: 'It branches left and right to feed both pulmonary lobes.',
        cameraPosition: [-0.6, 1.8, 3],
        cameraTarget: [-0.3, 1.1, -0.3],
        audioNarrationText: 'The Pulmonary Artery carries blood to the lungs. It is the only artery that carries oxygen-depleted blood.'
      },
      {
        stepNumber: 6,
        title: 'Left Atrium & Oxygenated Return',
        componentId: 'left_atrium',
        explanation: 'Freshly oxygenated blood returns from the lungs and enters the Left Atrium.',
        detailedNotes: 'Blood is now bright red and rich in oxygen, ready for systemic delivery.',
        cameraPosition: [1.6, 1.2, 3],
        cameraTarget: [0.8, 0.7, -0.2],
        audioNarrationText: 'Oxygen-rich blood returning from the lungs collects in the Left Atrium.'
      },
      {
        stepNumber: 7,
        title: 'Mitral (Bicuspid) Valve',
        componentId: 'mitral_valve',
        explanation: 'Blood passes through the Mitral Valve into the thick-walled Left Ventricle.',
        detailedNotes: 'The mitral valve must withstand high pressure during ventricular contraction.',
        cameraPosition: [0.8, 0.2, 2.5],
        cameraTarget: [0.4, 0.1, 0.2],
        audioNarrationText: 'The Mitral Valve regulates blood flow into the powerful Left Ventricle.'
      },
      {
        stepNumber: 8,
        title: 'Left Ventricle Powerhouse',
        componentId: 'left_ventricle',
        explanation: 'The Left Ventricle has a muscular wall 3 times thicker than the right. It generates high pressure to pump blood to the entire body.',
        detailedNotes: 'This chamber creates your systolic blood pressure reading (e.g. 120 mmHg).',
        cameraPosition: [1.2, -1.2, 3.2],
        cameraTarget: [0.6, -0.7, 0.2],
        audioNarrationText: 'The Left Ventricle is the most powerful chamber of the heart, pumping blood to the brain and entire body.'
      },
      {
        stepNumber: 9,
        title: 'The Aorta & Systemic Circulation',
        componentId: 'aorta',
        explanation: 'Blood surges into the Aorta, supplying oxygen and nutrients to every cell in your body. The cardiac cycle repeats ~72 times per minute!',
        detailedNotes: 'Aortic arch branches send blood upward to the head/brain and downward to systemic organs.',
        cameraPosition: [0.4, 2.2, 3.5],
        cameraTarget: [0.2, 1.4, 0.0],
        audioNarrationText: 'The Aorta distributes oxygen-rich blood through arteries across your entire body.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'Cardiac Cycle & Blood Flow Animation',
      simulationDescription: 'Simulates the rhythmic beating of cardiac muscle and continuous movement of blood cell particles through chambers and vessels.',
      type: 'flow',
      defaultSpeed: 1,
      particleCount: 120,
      particleColor: '#ef4444',
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: true,
        parameterSlider: {
          label: 'Heart Rate (BPM)',
          min: 40,
          max: 180,
          defaultVal: 72,
          unit: 'BPM'
        }
      }
    },
    quizzes: [
      {
        id: 'q1',
        question: 'Which heart chamber pumps deoxygenated blood to the lungs?',
        options: ['Left Ventricle', 'Right Ventricle', 'Left Atrium', 'Right Atrium'],
        correctIndex: 1,
        explanation: 'The Right Ventricle receives deoxygenated blood from the RA and pumps it into the Pulmonary Artery leading to the lungs.',
        relatedComponentId: 'right_ventricle'
      },
      {
        id: 'q2',
        question: 'Why is the Left Ventricle wall much thicker than the Right Ventricle?',
        options: [
          'It stores extra blood volume',
          'It must generate higher pressure to pump blood to the whole body',
          'It contains extra cardiac valves',
          'It receives venous blood directly'
        ],
        correctIndex: 1,
        explanation: 'Systemic arterial resistance is high (~120 mmHg) compared to pulmonary resistance (~25 mmHg), requiring thicker muscle fibers in the LV.',
        relatedComponentId: 'left_ventricle'
      },
      {
        id: 'q3',
        question: 'Which valve prevents backflow of blood into the Left Atrium?',
        options: ['Tricuspid Valve', 'Mitral (Bicuspid) Valve', 'Aortic Valve', 'Pulmonary Valve'],
        correctIndex: 1,
        explanation: 'The Mitral (Bicuspid) Valve sits between the Left Atrium and Left Ventricle.',
        relatedComponentId: 'mitral_valve'
      }
    ]
  },

  // 2. BIOLOGY - ANIMAL CELL & MITOCHONDRIA
  {
    id: 'cell_mitochondria',
    name: 'Animal Cell & Organelles',
    title: 'Eukaryotic Cell Structure & Organelles',
    subject: 'biology',
    difficulty: 'high_school',
    tags: ['cytology', 'cell biology', 'mitochondria', 'nucleus', 'dna', 'organelles', 'atp'],
    summary: 'Interactive 3D eukaryotic cell model showing Nucleus, Mitochondria, Golgi, ER, and Cytosol.',
    overviewText: 'Eukaryotic cells contain membrane-bound organelles that perform specialized metabolic tasks. Mitochondria generate ATP energy, the Nucleus houses genetic DNA, and the Endoplasmic Reticulum synthesizes proteins.',
    meshType: 'procedural_cell',
    sketchfabEmbedId: '36b41d2d3a3c467a96e386a3bf0be0e5',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'nucleus',
        name: 'Nucleus & Chromatin',
        label: 'Nucleus',
        description: 'Control center containing genomic DNA and the Nucleolus.',
        detailedExplanation: 'Enclosed by a double-membrane nuclear envelope with nuclear pores. Houses genetic code for cellular transcription.',
        functionText: 'Stores DNA and regulates gene expression and cell division.',
        importanceText: 'Mutations in nuclear DNA can lead to genetic disorders and neoplasia.',
        color: '#9333ea',
        highlightColor: '#c084fc',
        position: [0, 0, 0]
      },
      {
        id: 'mitochondria',
        name: 'Mitochondria (Powerhouse)',
        label: 'Mitochondria',
        description: 'Double-membraned organelle generating ATP through cellular respiration.',
        detailedExplanation: 'Contains inner folded cristae and mitochondrial matrix where Krebs cycle and Oxidative Phosphorylation occur.',
        functionText: 'Produces ATP (Adenosine Triphosphate) energy currency for cellular work.',
        importanceText: 'Defects lead to mitochondrial encephalomyopathies.',
        color: '#e11d48',
        highlightColor: '#fb7185',
        position: [1.2, 0.6, 0.4]
      },
      {
        id: 'endoplasmic_reticulum',
        name: 'Endoplasmic Reticulum (ER)',
        label: 'Endoplasmic Reticulum',
        description: 'Network of membranous tubules involved in protein & lipid synthesis.',
        detailedExplanation: 'Rough ER is studded with ribosomes for protein translation; Smooth ER synthesizes lipids and detoxifies metabolic byproducts.',
        functionText: 'Protein folding, transport, and lipid membrane synthesis.',
        importanceText: 'ER stress triggers unfolded protein response.',
        color: '#0284c7',
        highlightColor: '#38bdf8',
        position: [-1.1, -0.5, 0.3]
      },
      {
        id: 'golgi_apparatus',
        name: 'Golgi Apparatus',
        label: 'Golgi Body',
        description: 'Stack of flattened cisternae that modifies, sorts, and packages proteins for secretion.',
        detailedExplanation: 'Receives transport vesicles from ER at its cis-face, glycosylates proteins, and buds off secretory vesicles at trans-face.',
        functionText: 'Post-translational protein modification and vesicular trafficking.',
        importanceText: 'Essential for enzyme secretion and lysosome formation.',
        color: '#16a34a',
        highlightColor: '#4ade80',
        position: [0.8, -1.0, -0.2]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'Cell Overview',
        componentId: 'nucleus',
        explanation: 'Eukaryotic animal cells are organized compartmental units with specialized membrane-bound organelles.',
        cameraPosition: [0, 0, 5],
        audioNarrationText: 'Welcome to the animal cell model. Notice the central nucleus and surrounding organelles.'
      },
      {
        stepNumber: 2,
        title: 'Nucleus & Genetic Material',
        componentId: 'nucleus',
        explanation: 'The Nucleus houses DNA organized into chromosomes.',
        cameraPosition: [0, 0, 3],
        audioNarrationText: 'The nucleus acts as the command center containing the master DNA genome.'
      },
      {
        stepNumber: 3,
        title: 'Mitochondria & Cellular Respiration',
        componentId: 'mitochondria',
        explanation: 'Mitochondria convert glucose and oxygen into ATP energy molecules through oxidative phosphorylation.',
        cameraPosition: [1.8, 0.8, 3],
        audioNarrationText: 'Mitochondria generate ATP energy to fuel all biochemical processes in the body.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'ATP Synthesis & Vesicular Transport',
      simulationDescription: 'Visualizes ATP molecules synthesizing inside mitochondria and vesicles floating along microtubules.',
      type: 'signal',
      defaultSpeed: 1,
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: false
      }
    },
    quizzes: [
      {
        id: 'cq1',
        question: 'Which organelle is known as the powerhouse of the cell?',
        options: ['Nucleus', 'Mitochondria', 'Golgi Body', 'Lysosome'],
        correctIndex: 1,
        explanation: 'Mitochondria generate ATP through cellular respiration.',
        relatedComponentId: 'mitochondria'
      }
    ]
  },

  // 3. CHEMISTRY - DNA DOUBLE HELIX & MOLECULES
  {
    id: 'dna_helix',
    name: 'DNA Double Helix',
    title: 'Deoxyribonucleic Acid Molecular Architecture',
    subject: 'chemistry',
    difficulty: 'high_school',
    tags: ['genetics', 'dna', 'molecular biology', 'adenine', 'thymine', 'guanine', 'cytosine', 'hydrogen bonds'],
    summary: '3D twisted antiparallel double helix featuring Watson-Crick base pairing (A-T, G-C).',
    overviewText: 'DNA consists of two antiparallel polynucleotide strands twisted into a right-handed double helix. Nitrogenous bases (Adenine, Thymine, Guanine, Cytosine) pair specifically via hydrogen bonds across the major and minor grooves.',
    meshType: 'procedural_dna',
    sketchfabEmbedId: 'bf5aa0eb8d7a4cb2820a133f9dd49ea3',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'adenine_thymine',
        name: 'Adenine - Thymine Base Pair (A-T)',
        label: 'A-T Base Pair',
        description: 'Purine Adenine pairs with Pyrimidine Thymine via 2 hydrogen bonds.',
        detailedExplanation: 'Watson-Crick pairing rule: Adenine forms 2 electrostatic hydrogen bonds with Thymine.',
        functionText: 'Genetic coding letter pair.',
        importanceText: 'Melts at lower temperatures than G-C pairs due to fewer hydrogen bonds.',
        color: '#f59e0b',
        highlightColor: '#fbbf24',
        position: [0, 0.8, 0]
      },
      {
        id: 'guanine_cytosine',
        name: 'Guanine - Cytosine Base Pair (G-C)',
        label: 'G-C Base Pair',
        description: 'Purine Guanine pairs with Pyrimidine Cytosine via 3 hydrogen bonds.',
        detailedExplanation: 'G-C pairs are joined by 3 hydrogen bonds, imparting greater thermal stability to high-GC DNA sequences.',
        functionText: 'High-stability genetic base pairing.',
        importanceText: 'Increases melting temperature (Tm) of genomic DNA.',
        color: '#10b981',
        highlightColor: '#34d399',
        position: [0, -0.4, 0]
      },
      {
        id: 'sugar_phosphate_backbone',
        name: 'Sugar-Phosphate Backbone',
        label: 'Sugar-Phosphate Backbone',
        description: 'Outer helical structural frame formed by alternating 2-deoxyribose and phosphate groups.',
        detailedExplanation: 'Covalent phosphodiester bonds link 5\' carbon of one sugar to 3\' carbon of the next, establishing 5\' to 3\' directionality.',
        functionText: 'Provides structural backbone and negative charge.',
        importanceText: 'Protected from enzymatic cleavage inside nucleosomes.',
        color: '#0ea5e9',
        highlightColor: '#38bdf8',
        position: [0.8, 0, 0]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'Double Helix Structure',
        componentId: 'sugar_phosphate_backbone',
        explanation: 'Discovered by Watson, Crick, and Franklin, DNA forms a twisted ladder called a double helix.',
        cameraPosition: [0, 0, 5],
        audioNarrationText: 'This is the molecular double helix of DNA, carrying the code for life.'
      },
      {
        stepNumber: 2,
        title: 'Complementary Base Pairing',
        componentId: 'adenine_thymine',
        explanation: 'Adenine (A) always pairs with Thymine (T) via 2 hydrogen bonds, while Guanine (G) pairs with Cytosine (C) via 3 hydrogen bonds.',
        cameraPosition: [0, 0.8, 3],
        audioNarrationText: 'Base pairing rules ensure precise genetic replication during cell division.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'Helical Rotation & Unzipping (Replication)',
      simulationDescription: 'Simulates continuous rotation of the double helix and replication fork unzipping.',
      type: 'rotation',
      defaultSpeed: 1,
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: true
      }
    },
    quizzes: [
      {
        id: 'dna_q1',
        question: 'How many hydrogen bonds connect Guanine and Cytosine in DNA?',
        options: ['1', '2', '3', '4'],
        correctIndex: 2,
        explanation: 'Guanine and Cytosine form 3 hydrogen bonds, making G-C rich DNA more stable.',
        relatedComponentId: 'guanine_cytosine'
      }
    ]
  },

  // 4. PHYSICS & ASTRONOMY - SOLAR SYSTEM
  {
    id: 'solar_system',
    name: 'Solar System & Planetary Orbits',
    title: 'Heliocentric Solar System Architecture',
    subject: 'astronomy',
    difficulty: 'elementary',
    tags: ['astronomy', 'planets', 'sun', 'earth', 'jupiter', 'orbits', 'gravitation', 'kepler laws'],
    summary: 'Interactive 3D model of the Sun and eight planets executing Keplerian orbital movement.',
    overviewText: 'Our solar system consists of the Sun, four terrestrial inner planets (Mercury, Venus, Earth, Mars), and four outer giant planets (Jupiter, Saturn, Uranus, Neptune) orbiting in elliptical paths governed by gravity.',
    meshType: 'procedural_solar_system',
    sketchfabEmbedId: 'c9f3237a89044b209d73d6b1d161d2d2',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'sun',
        name: 'The Sun (Sol)',
        label: 'Sun',
        description: 'G2V main-sequence yellow dwarf star at the gravitational center of our solar system.',
        detailedExplanation: 'Fuses 600 million tons of hydrogen into helium every second in its thermonuclear core at 15 million °C.',
        functionText: 'Provides 99.86% of solar system mass and light/heat energy.',
        importanceText: 'Primary energy source for weather, photosynthesis, and life on Earth.',
        color: '#eab308',
        highlightColor: '#fde047',
        position: [0, 0, 0]
      },
      {
        id: 'earth',
        name: 'Planet Earth & Moon',
        label: 'Earth',
        description: 'Third planet from the Sun; the only known habitable world with liquid surface water.',
        detailedExplanation: 'Possesses a dynamic nitrogen-oxygen atmosphere, protective magnetosphere, and a single large satellite (Moon).',
        functionText: 'Habitable zone terrestrial planet.',
        importanceText: 'Home world supporting biosphere and humanity.',
        color: '#2563eb',
        highlightColor: '#60a5fa',
        position: [1.8, 0, 0]
      },
      {
        id: 'jupiter',
        name: 'Jupiter (Gas Giant)',
        label: 'Jupiter',
        description: 'Largest planet; gas giant composed mainly of hydrogen and helium with the Great Red Spot storm.',
        detailedExplanation: 'Mass is 2.5 times that of all other planets combined. Acts as a gravitational shield against asteroids.',
        functionText: 'Gas giant planetary dynamic body.',
        importanceText: 'Prevents many comets from striking inner terrestrial planets.',
        color: '#d97706',
        highlightColor: '#f59e0b',
        position: [3.2, 0, 0]
      },
      {
        id: 'saturn',
        name: 'Saturn & Ring System',
        label: 'Saturn',
        description: 'Famous gas giant encircled by prominent ice particle rings.',
        detailedExplanation: 'Rings are made of water ice particles ranging from micrometers to meters in size.',
        functionText: 'Ringed gas giant planet.',
        importanceText: 'Key target for Cassini exploration and planetary science.',
        color: '#ca8a04',
        highlightColor: '#facc15',
        position: [4.2, 0, 0]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'The Solar System Center',
        componentId: 'sun',
        explanation: 'The Sun holds 99.8% of all mass in the solar system, exerting gravitational dominance over all orbiting planets.',
        cameraPosition: [0, 4, 8],
        audioNarrationText: 'The Sun is the massive star at the center of our planetary system.'
      },
      {
        stepNumber: 2,
        title: 'Planet Earth & Habitable Zone',
        componentId: 'earth',
        explanation: 'Earth orbits in the circumstellar Goldilocks zone where water remains liquid on the surface.',
        cameraPosition: [2.5, 1, 4],
        audioNarrationText: 'Earth orbits in the Goldilocks zone where temperatures allow liquid water and life.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'Keplerian Planetary Orbital Motion',
      simulationDescription: 'Simulates planetary revolution around the Sun with realistic speed ratios.',
      type: 'orbit',
      defaultSpeed: 1,
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: false,
        parameterSlider: {
          label: 'Orbital Speed Multiple',
          min: 0.1,
          max: 10,
          defaultVal: 1,
          unit: 'x'
        }
      }
    },
    quizzes: [
      {
        id: 'ss_q1',
        question: 'Which is the largest planet in our solar system?',
        options: ['Saturn', 'Jupiter', 'Neptune', 'Earth'],
        correctIndex: 1,
        explanation: 'Jupiter is the massive gas giant with 318 times the mass of Earth.',
        relatedComponentId: 'jupiter'
      }
    ]
  },

  // 5. ENGINEERING - FOUR STROKE INTERNAL COMBUSTION ENGINE
  {
    id: 'engine_4stroke',
    name: '4-Stroke Engine',
    title: 'Internal Combustion Engine & Mechanical Transmission',
    subject: 'engineering',
    difficulty: 'college_mbbs',
    tags: ['engineering', 'mechanical', 'thermodynamics', 'piston', 'crankshaft', 'combustion', 'valves', 'automotive'],
    summary: 'Interactive mechanical assembly showing Intake, Compression, Power, and Exhaust stroke cycles.',
    overviewText: 'A 4-stroke internal combustion engine converts thermal energy from fuel combustion into mechanical rotational kinetic energy via Otto cycle thermodynamics across four distinct strokes.',
    meshType: 'procedural_engine',
    sketchfabEmbedId: '012fb1a520bf4f8a846c483a9bd4d3aa',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'piston',
        name: 'Piston & Connecting Rod',
        label: 'Piston Assembly',
        description: 'Reciprocating component that moves up and down inside the cylinder.',
        detailedExplanation: 'Transmits gas pressure expansion force from fuel combustion down to the wrist pin and connecting rod.',
        functionText: 'Converts gas expansion into linear stroke motion.',
        importanceText: 'Subjected to intense thermal and mechanical stress.',
        color: '#94a3b8',
        highlightColor: '#cbd5e1',
        position: [0, 0, 0]
      },
      {
        id: 'crankshaft',
        name: 'Crankshaft',
        label: 'Crankshaft',
        description: 'Rotational shaft that converts linear piston stroke into rotational torque.',
        detailedExplanation: 'Equipped with counterweights to minimize vibration during high-RPM operation.',
        functionText: 'Transforms reciprocating motion to rotational output.',
        importanceText: 'Drives vehicle transmission and wheels.',
        color: '#64748b',
        highlightColor: '#94a3b8',
        position: [0, -1.2, 0]
      },
      {
        id: 'spark_plug',
        name: 'Spark Plug',
        label: 'Spark Plug',
        description: 'Delivers electric high-voltage spark to ignite compressed air-fuel mixture.',
        detailedExplanation: 'Fires a 20,000V electric arc at the top of the compression stroke.',
        functionText: 'Ignites combustion chamber gas.',
        importanceText: 'Misfires lead to power loss and emissions.',
        color: '#ef4444',
        highlightColor: '#f87171',
        position: [0, 1.4, 0]
      },
      {
        id: 'intake_valve',
        name: 'Intake Valve',
        label: 'Intake Valve',
        description: 'Opens to allow fresh air-fuel mixture into the combustion chamber.',
        detailedExplanation: 'Actuated by camshaft lobes against spring tension.',
        functionText: 'Admits air-fuel charge during intake stroke.',
        importanceText: 'Valvular timing determines volumetric efficiency.',
        color: '#3b82f6',
        highlightColor: '#60a5fa',
        position: [-0.5, 1.2, 0]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'The 4-Stroke Cycle Overview',
        componentId: 'piston',
        explanation: 'The Otto cycle engine repeats 4 steps: 1. Intake, 2. Compression, 3. Power (Spark Combustion), 4. Exhaust.',
        cameraPosition: [0, 0, 5],
        audioNarrationText: 'An internal combustion engine transforms fuel explosion into mechanical rotation across four strokes.'
      },
      {
        stepNumber: 2,
        title: 'Power Stroke & Spark Ignition',
        componentId: 'spark_plug',
        explanation: 'At top dead center (TDC), the spark plug fires, rapidly burning compressed fuel and slamming the piston down.',
        cameraPosition: [0, 1.5, 3],
        audioNarrationText: 'The spark plug ignites compressed fuel, generating high pressure that drives the piston down.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'Piston Stroke & Crankshaft Rotation',
      simulationDescription: 'Simulates synchronized valve opening, piston movement, spark flash, and crankshaft spinning.',
      type: 'piston',
      defaultSpeed: 1,
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: true,
        parameterSlider: {
          label: 'Engine RPM',
          min: 300,
          max: 6000,
          defaultVal: 1200,
          unit: 'RPM'
        }
      }
    },
    quizzes: [
      {
        id: 'eng_q1',
        question: 'Which component converts linear piston movement into rotational force?',
        options: ['Spark Plug', 'Camshaft', 'Crankshaft', 'Fuel Injector'],
        correctIndex: 2,
        explanation: 'The Crankshaft converts up-and-down piston stroke into rotational torque.',
        relatedComponentId: 'crankshaft'
      }
    ]
  },

  // 6. PHYSICS - ATOMIC STRUCTURE (BOHR ATOM)
  {
    id: 'bohr_atom',
    name: 'Atomic Structure (Bohr Atom)',
    title: 'Quantum Atomic Structure & Subatomic Particles',
    subject: 'physics',
    difficulty: 'high_school',
    tags: ['physics', 'chemistry', 'atom', 'electrons', 'protons', 'neutrons', 'quantum', 'bohr model'],
    summary: '3D Rutherford-Bohr atom with central Nucleus (protons + neutrons) and orbiting electron shells.',
    overviewText: 'An atom comprises a dense central nucleus of positively charged Protons and neutral Neutrons, surrounded by negatively charged Electrons orbiting in discrete quantum energy levels.',
    meshType: 'procedural_atom',
    sketchfabEmbedId: '4005cf3ee98a44d081bc13ff85caed55',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'nucleus_core',
        name: 'Atomic Nucleus',
        label: 'Nucleus',
        description: 'Dense central core held together by the Strong Nuclear Force.',
        detailedExplanation: 'Contains Protons (+1 charge) and Neutrons (0 charge). Contains over 99.9% of the total atomic mass.',
        functionText: 'Central mass and positive electrical charge anchor.',
        importanceText: 'Nuclear fusion/fission alters nuclear stability.',
        color: '#dc2626',
        highlightColor: '#ef4444',
        position: [0, 0, 0]
      },
      {
        id: 'electrons_orbit',
        name: 'Electron Shells & Orbitals',
        label: 'Electrons',
        description: 'Negative subatomic particles revolving in quantized energy shells.',
        detailedExplanation: 'Electrons occupy specific discrete energy levels (n=1, n=2, n=3). Jumping between levels absorbs or emits photons.',
        functionText: 'Determines chemical bonding, reactivity, and valence.',
        importanceText: 'Valence electrons govern all chemical reaction kinetics.',
        color: '#06b6d4',
        highlightColor: '#22d3ee',
        position: [1.5, 0, 0]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'Atomic Nucleus',
        componentId: 'nucleus_core',
        explanation: 'The atomic nucleus sits at the center, packed with protons and neutrons.',
        cameraPosition: [0, 0, 4],
        audioNarrationText: 'At the heart of every atom lies a dense nucleus composed of protons and neutrons.'
      },
      {
        stepNumber: 2,
        title: 'Electron Energy Shells',
        componentId: 'electrons_orbit',
        explanation: 'Electrons orbit high-speed around the nucleus in quantum probability shells.',
        cameraPosition: [0, 0, 5],
        audioNarrationText: 'Electrons orbit the nucleus in quantized energy shells that govern chemical reactions.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'Electron Quantum Orbital Motion',
      simulationDescription: 'Simulates electrons spinning rapidly along orbital planes around the nucleus.',
      type: 'orbit',
      defaultSpeed: 1,
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: false
      }
    },
    quizzes: [
      {
        id: 'atom_q1',
        question: 'Which subatomic particle carries a negative electric charge?',
        options: ['Proton', 'Neutron', 'Electron', 'Alpha particle'],
        correctIndex: 2,
        explanation: 'Electrons carry a -1 elementary charge and orbit the positive nucleus.',
        relatedComponentId: 'electrons_orbit'
      }
    ]
  },

  // 7. GEOGRAPHY - EARTH LAYERS & TECTONICS
  {
    id: 'earth_layers',
    name: "Layers of the Earth",
    title: 'Geological Cross-Section & Tectonic Layers',
    subject: 'geography',
    difficulty: 'elementary',
    tags: ['geography', 'geology', 'crust', 'mantle', 'outer core', 'inner core', 'tectonics', 'earthquakes'],
    summary: 'Cross-section of Earth revealing the Crust, Mantle, Liquid Outer Core, and Solid Inner Core.',
    overviewText: 'Earth is structured into concentric physical layers: the thin solid Crust, viscous convective Mantle, liquid iron-nickel Outer Core, and solid superheated Inner Core.',
    meshType: 'procedural_earth',
    sketchfabEmbedId: 'd54a2ed8f4ee408f92bd51b038faeb7e',
    arSupported: true,
    vrSupported: true,
    parts: [
      {
        id: 'crust',
        name: 'Lithosphere & Crust',
        label: 'Crust',
        description: 'Thin outer solid rock layer (5-70 km thick) where tectonic plates float.',
        detailedExplanation: 'Divided into continental crust (granitic) and oceanic crust (basaltic).',
        functionText: 'Surface solid habitat and tectonic platform.',
        importanceText: 'Plate movement causes earthquakes, mountain building, and volcanism.',
        color: '#15803d',
        highlightColor: '#22c55e',
        position: [0, 1.5, 0]
      },
      {
        id: 'mantle',
        name: 'Convective Mantle',
        label: 'Mantle',
        description: 'Thickest layer (~2,900 km) of semi-molten silicate rock exhibiting slow thermal convection.',
        detailedExplanation: 'Convection currents in the asthenosphere drive continental drift and seafloor spreading.',
        functionText: 'Thermal engine driving plate tectonics.',
        importanceText: 'Generates volcanic magma plumes.',
        color: '#f97316',
        highlightColor: '#fb923c',
        position: [0, 0.8, 0]
      },
      {
        id: 'outer_core',
        name: 'Liquid Outer Core',
        label: 'Outer Core',
        description: 'Liquid iron and nickel layer (~2,200 km thick) generating Earth magnetic field.',
        detailedExplanation: 'Convective motion of conductive liquid iron creates geodynamo action protecting Earth from solar wind.',
        functionText: 'Geodynamo magnetosphere generator.',
        importanceText: 'Protects atmosphere from cosmic radiation stripping.',
        color: '#ef4444',
        highlightColor: '#f87171',
        position: [0, 0.2, 0]
      },
      {
        id: 'inner_core',
        name: 'Solid Inner Core',
        label: 'Inner Core',
        description: 'Solid sphere of iron-nickel at 5,400 °C kept solid by extreme gravitational pressure.',
        detailedExplanation: 'Pressure is 3.6 million atmospheres, preventing iron from melting despite sun-surface temperatures.',
        functionText: 'Gravitational center anchor.',
        importanceText: 'Grows slowly as outer core cools over billions of years.',
        color: '#facc15',
        highlightColor: '#fde047',
        position: [0, -0.4, 0]
      }
    ],
    guidedLesson: [
      {
        stepNumber: 1,
        title: 'Earth Layer Cross-Section',
        componentId: 'crust',
        explanation: 'Earth contains 4 major layers: Crust, Mantle, Outer Core, and Inner Core.',
        cameraPosition: [0, 0, 5],
        audioNarrationText: 'Let us peel back Earth layers from the outer crust to the solid inner core.'
      },
      {
        stepNumber: 2,
        title: 'Outer Core & Magnetic Field',
        componentId: 'outer_core',
        explanation: 'Liquid iron swirling in the outer core generates Earth magnetosphere shielding us from radiation.',
        cameraPosition: [0, 0.2, 3],
        audioNarrationText: 'The liquid outer core acts as a giant dynamo generating Earth magnetic field.'
      }
    ],
    simulation: {
      hasSimulation: true,
      simulationTitle: 'Mantle Convection & Geodynamo',
      simulationDescription: 'Visualizes heat convection currents in the mantle and magnetic field lines emerging from the core.',
      type: 'flow',
      defaultSpeed: 1,
      controlsSupported: {
        playPause: true,
        speedControl: true,
        stepByStep: false
      }
    },
    quizzes: [
      {
        id: 'geog_q1',
        question: 'Which Earth layer generates our magnetic field?',
        options: ['Crust', 'Mantle', 'Liquid Outer Core', 'Solid Inner Core'],
        correctIndex: 2,
        explanation: 'Swirling liquid iron in the Outer Core generates the geodynamo magnetic field.',
        relatedComponentId: 'outer_core'
      }
    ]
  }
];

export function get3DModelById(id: string): Learning3DModel | undefined {
  return LEARNING_3D_MODELS.find(m => m.id === id);
}

export function search3DModels(query: string): Learning3DModel[] {
  const q = query.toLowerCase().trim();
  if (!q) return LEARNING_3D_MODELS;
  return LEARNING_3D_MODELS.filter(m => 
    m.name.toLowerCase().includes(q) ||
    m.title.toLowerCase().includes(q) ||
    m.summary.toLowerCase().includes(q) ||
    m.subject.toLowerCase().includes(q) ||
    m.tags.some(t => t.toLowerCase().includes(q))
  );
}
