import React, { useState } from 'react';
import { 
  ArrowLeft, 
  Share2, 
  Download, 
  MoreVertical, 
  Calendar, 
  Clock, 
  Users, 
  MapPin, 
  Sparkles, 
  CheckCircle2, 
  FileText, 
  Play, 
  Pause, 
  ArrowRight, 
  Send,
  Check,
  ChevronDown
} from 'lucide-react';
import ArohiMeetLogo from './ArohiMeetLogo';
import ArohiMeetAvatar from './ArohiMeetAvatar';
import { MeetingSession, getInitials, getAvatarColor } from './meetData';

interface MeetPostMeetingViewProps {
  meeting: MeetingSession;
  onBack: () => void;
  onOpenAskArohi: (initialQuery?: string) => void;
  onOpenTranscript: () => void;
}

export const MeetPostMeetingView: React.FC<MeetPostMeetingViewProps> = ({
  meeting,
  onBack,
  onOpenAskArohi,
  onOpenTranscript
}) => {
  const [activeTab, setActiveTab] = useState<'summary' | 'agenda' | 'discussion' | 'decisions' | 'actions' | 'participants'>('summary');
  
  // Interactive action item status toggles
  const [actionItems, setActionItems] = useState(meeting.actionItems);
  
  // Audio playback scrubber state
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [playbackProgress, setPlaybackProgress] = useState(25);
  const [playbackSpeed, setPlaybackSpeed] = useState('1x');
  
  // Ask Arohi inline question
  const [askArohiInput, setAskArohiInput] = useState('');

  const toggleActionStatus = (id: string) => {
    setActionItems((prev) =>
      prev.map((item) => {
        if (item.id === id) {
          const nextStatus = item.status === 'Completed' ? 'Pending' : item.status === 'Pending' ? 'In Progress' : 'Completed';
          return { ...item, status: nextStatus };
        }
        return item;
      })
    );
  };

  const handleDownloadMOM = () => {
    const content = `# MINUTES OF MEETING: ${meeting.title.toUpperCase()}
Date: ${meeting.date}
Timing: ${meeting.timeRange}
Duration: ${meeting.durationFormatted}
Participants: ${meeting.participantsCount}
Chairperson: ${meeting.organizer}

---

## EXECUTIVE SUMMARY
${meeting.executiveSummary}

## KEY DECISIONS
${meeting.decisions.map((d, i) => `${i + 1}. [${d.status}] ${d.title}`).join('\n')}

## ACTION ITEMS
${actionItems.map((a) => `- [${a.status.toUpperCase()}] ${a.task} | Assigned to: ${a.assignee} (Due: ${a.dueDate})`).join('\n')}

---
Generated by Arohi MEET™ — Institutional Intelligence Engine.
`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `MOM_${meeting.title.replace(/\s+/g, '_')}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="relative min-h-[92vh] w-full flex flex-col justify-between bg-[#070B14] text-white select-none pb-16 overflow-x-hidden">
      {/* Background Glow */}
      <div className="absolute top-0 right-10 w-96 h-96 bg-cyan-600/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute top-1/2 left-0 w-80 h-80 bg-purple-600/10 rounded-full blur-[120px] pointer-events-none" />

      {/* Top Bar with Status Badge & Actions */}
      <div className="w-full px-4 sm:px-6 py-3 flex items-center justify-between border-b border-slate-800 bg-[#070B14]/90 backdrop-blur-md z-30">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="p-1.5 rounded-full bg-slate-900 border border-slate-800 text-slate-300 hover:text-white"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>

          <ArohiMeetLogo size="sm" showTagline={false} />

          {/* AI Minutes Generated Badge */}
          <div className="hidden sm:flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold">
            <Check className="w-3.5 h-3.5" />
            <span>AI Minutes Generated in {meeting.aiMinutesGeneratedTime || '28 seconds'}</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              navigator.clipboard.writeText(window.location.href);
              alert('Link copied to clipboard!');
            }}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-900 border border-slate-700 text-xs text-slate-200 hover:border-cyan-400/50 transition"
          >
            <Share2 className="w-3.5 h-3.5 text-cyan-400" />
            <span className="hidden sm:inline">Share</span>
          </button>

          <button
            onClick={handleDownloadMOM}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-semibold text-xs shadow-md hover:scale-105 active:scale-95 transition"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download MOM</span>
          </button>

          <button className="p-1.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-400 hover:text-white">
            <MoreVertical className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Main Container */}
      <div className="w-full max-w-5xl mx-auto px-4 sm:px-6 pt-5 flex-1">
        {/* Meeting Title & Meta Info */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800/80 mb-4">
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
              {meeting.title}
            </h1>
            <div className="flex flex-wrap items-center gap-3 text-xs text-slate-400 mt-1.5">
              <span className="flex items-center gap-1 text-slate-300">
                <Calendar className="w-3.5 h-3.5 text-cyan-400" />
                {meeting.date}
              </span>
              <span>•</span>
              <span className="flex items-center gap-1 text-slate-300">
                <Clock className="w-3.5 h-3.5 text-purple-400" />
                {meeting.timeRange}
              </span>
              <span>•</span>
              <span className="flex items-center gap-1 text-slate-300">
                <Users className="w-3.5 h-3.5 text-emerald-400" />
                {meeting.participantsCount} Participants
              </span>
              <span>•</span>
              <span className="flex items-center gap-1 text-slate-300">
                <MapPin className="w-3.5 h-3.5 text-amber-400" />
                {meeting.location}
              </span>
            </div>
          </div>

          {/* Neon Slogan Badge */}
          <div className="p-2.5 rounded-xl bg-purple-950/20 border border-purple-500/20 text-purple-300 font-serif italic text-xs self-start sm:self-auto">
            Ideas Decisions Action Together ✦
          </div>
        </div>

        {/* Navigation Tabs Pill Row */}
        <div className="flex items-center gap-2 overflow-x-auto no-scrollbar pb-3 mb-4">
          {(['summary', 'agenda', 'discussion', 'decisions', 'actions', 'participants'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-1.5 rounded-full text-xs font-semibold capitalize transition ${
                activeTab === tab
                  ? 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-[0_0_15px_rgba(6,182,212,0.4)]'
                  : 'bg-slate-900 border border-slate-800 text-slate-400 hover:text-slate-200'
              }`}
            >
              {tab === 'actions' ? 'Action Items' : tab}
            </button>
          ))}
        </div>

        {/* Executive Summary Card (✦ AI Generated) */}
        <div className="p-4 rounded-2xl bg-gradient-to-br from-indigo-950/40 via-slate-900/90 to-[#0c1224] border border-cyan-500/30 mb-5 relative overflow-hidden shadow-lg">
          <div className="flex items-center justify-between mb-2">
            <h2 className="text-xs font-bold uppercase tracking-wider text-cyan-400 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              Executive Summary (AI Generated)
            </h2>
            <span className="text-[10px] text-slate-400">98% Accuracy</span>
          </div>
          <p className="text-xs sm:text-sm text-slate-200 leading-relaxed font-light">
            {meeting.executiveSummary}
          </p>
        </div>

        {/* 4 Metric KPI Cards (Screen 6) */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
          {/* Participants */}
          <div className="p-3.5 rounded-2xl bg-[#0c1224]/80 border border-slate-800 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-slate-400">Participants</span>
              <Users className="w-4 h-4 text-cyan-400" />
            </div>
            <p className="text-xl font-black text-white">{meeting.participants?.length || 1}</p>
            <button
              onClick={() => setActiveTab('participants')}
              className="text-[10px] text-cyan-400 hover:underline flex items-center gap-0.5 mt-2"
            >
              View All →
            </button>
          </div>

          {/* Decisions Taken */}
          <div className="p-3.5 rounded-2xl bg-[#0c1224]/80 border border-slate-800 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-slate-400">Decisions Taken</span>
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            </div>
            <p className="text-xl font-black text-emerald-400">{meeting.decisions.length}</p>
            <button
              onClick={() => setActiveTab('decisions')}
              className="text-[10px] text-emerald-400 hover:underline flex items-center gap-0.5 mt-2"
            >
              View Details →
            </button>
          </div>

          {/* Action Items */}
          <div className="p-3.5 rounded-2xl bg-[#0c1224]/80 border border-slate-800 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-slate-400">Action Items</span>
              <FileText className="w-4 h-4 text-purple-400" />
            </div>
            <p className="text-xl font-black text-purple-400">{actionItems.length}</p>
            <button
              onClick={() => setActiveTab('actions')}
              className="text-[10px] text-purple-400 hover:underline flex items-center gap-0.5 mt-2"
            >
              View Details →
            </button>
          </div>

          {/* Duration */}
          <div className="p-3.5 rounded-2xl bg-[#0c1224]/80 border border-slate-800 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-slate-400">Meeting Duration</span>
              <Clock className="w-4 h-4 text-amber-400" />
            </div>
            <p className="text-xl font-black text-amber-400">{meeting.durationFormatted}</p>
            <button
              onClick={() => setIsPlayingAudio(!isPlayingAudio)}
              className="text-[10px] text-amber-400 hover:underline flex items-center gap-0.5 mt-2"
            >
              Play Recording →
            </button>
          </div>
        </div>

        {/* 2-Column Section: Left Decisions & Actions | Right Participants & Recording */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
          {/* Left Column (2/3): Key Decisions & Action Items */}
          <div className="lg:col-span-2 space-y-4">
            {/* Key Decisions */}
            <div className="p-4 rounded-2xl bg-[#0c1224]/90 border border-slate-800">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                  Key Decisions
                </h3>
                <span className="text-xs text-slate-400">View All ({meeting.decisions.length})</span>
              </div>

              <div className="space-y-2">
                {meeting.decisions.length === 0 ? (
                  <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-center text-xs text-slate-400">
                    No formal resolutions recorded for this session. Use the Ask Arohi Copilot below to generate custom decisions.
                  </div>
                ) : (
                  meeting.decisions.map((d) => (
                    <div
                      key={d.id}
                      className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex items-start justify-between gap-3 text-xs"
                    >
                      <div className="flex items-start gap-2">
                        <span className="w-5 h-5 rounded-full bg-slate-800 text-slate-400 font-bold text-[10px] flex items-center justify-center flex-shrink-0 mt-0.5">
                          {d.number}
                        </span>
                        <div>
                          <p className="font-semibold text-slate-200">{d.title}</p>
                          {d.proposedBy && (
                            <p className="text-[10px] text-slate-500 mt-0.5">
                              Proposed by: <span className="text-slate-400">{d.proposedBy}</span>
                            </p>
                          )}
                        </div>
                      </div>

                      <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 flex-shrink-0">
                        {d.status}
                      </span>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Action Items Register */}
            <div className="p-4 rounded-2xl bg-[#0c1224]/90 border border-slate-800">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                  <FileText className="w-3.5 h-3.5 text-purple-400" />
                  Action Items
                </h3>
                <span className="text-xs text-slate-400">View All ({actionItems.length})</span>
              </div>

              <div className="space-y-2.5">
                {actionItems.length === 0 ? (
                  <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-center text-xs text-slate-400">
                    No pending action items assigned. Click below to add or ask Arohi to draft next steps.
                  </div>
                ) : (
                  actionItems.map((item) => (
                    <div
                      key={item.id}
                      className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex items-center justify-between gap-3 text-xs"
                    >
                      <div className="flex-1">
                        <p className="font-medium text-white">{item.task}</p>
                        <div className="flex items-center gap-3 text-[10px] text-slate-400 mt-1">
                          <span>Assignee: <strong className="text-cyan-400">{item.assignee}</strong></span>
                          <span>•</span>
                          <span>Due: <strong className="text-purple-300">{item.dueDate}</strong></span>
                        </div>
                      </div>

                      <button
                        onClick={() => toggleActionStatus(item.id)}
                        className={`px-2.5 py-1 rounded-full text-[10px] font-semibold transition ${
                          item.status === 'Completed'
                            ? 'bg-emerald-500/15 border border-emerald-500/40 text-emerald-400'
                            : item.status === 'In Progress'
                            ? 'bg-amber-500/15 border border-amber-500/40 text-amber-400'
                            : 'bg-purple-500/15 border border-purple-500/40 text-purple-400'
                        }`}
                      >
                        {item.status}
                      </button>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>

          {/* Right Column (1/3): Participants & Recording Audio Player */}
          <div className="space-y-4">
            {/* Participants Card */}
            <div className="p-4 rounded-2xl bg-[#0c1224]/90 border border-slate-800">
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-xs font-bold text-white uppercase tracking-wider">
                  Participants
                </h4>
                <span className="text-xs text-slate-400">{meeting.participants?.length || 1} total</span>
              </div>

              <div className="space-y-2.5">
                {(meeting.participants || []).slice(0, 5).map((p) => (
                  <div key={p.id} className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      {p.avatar ? (
                        <img
                          src={p.avatar}
                          alt={p.name}
                          className="w-7 h-7 rounded-full object-cover border border-slate-700"
                        />
                      ) : (
                        <div
                          style={{ backgroundColor: p.avatarColor || getAvatarColor(p.name) }}
                          className="w-7 h-7 rounded-full flex items-center justify-center text-white text-[10px] font-bold shadow"
                        >
                          {p.initials || getInitials(p.name)}
                        </div>
                      )}
                      <div>
                        <p className="font-medium text-white">{p.name}</p>
                        <p className="text-[10px] text-slate-500">{p.role}</p>
                      </div>
                    </div>
                  </div>
                ))}
                {(meeting.participants?.length || 0) > 5 && (
                  <div className="pt-1 text-[11px] text-cyan-400 hover:underline cursor-pointer">
                    + {(meeting.participants?.length || 0) - 5} more participants
                  </div>
                )}
              </div>
            </div>

            {/* Meeting Recording Audio Player (Screen 6) */}
            <div className="p-4 rounded-2xl bg-[#0c1224]/90 border border-slate-800">
              <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2">
                Meeting Recording
              </h4>

              {/* Fake Audio Waveform */}
              <div className="h-10 flex items-center justify-between gap-1 px-1 my-2 bg-slate-950 rounded-xl p-2">
                {[14, 28, 18, 36, 22, 16, 30, 24, 18, 34, 20, 28, 14, 32, 22, 16, 26, 18].map((h, i) => (
                  <span
                    key={i}
                    style={{ height: `${h}px` }}
                    className={`w-1 rounded-full ${
                      i < 8 ? 'bg-cyan-400' : 'bg-slate-700'
                    }`}
                  />
                ))}
              </div>

              {/* Player Controls */}
              <div className="flex items-center justify-between text-xs text-slate-400">
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setIsPlayingAudio(!isPlayingAudio)}
                    className="w-8 h-8 rounded-full bg-cyan-500 hover:bg-cyan-400 text-slate-950 flex items-center justify-center font-bold"
                  >
                    {isPlayingAudio ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4 ml-0.5" />}
                  </button>
                  <span className="font-mono text-[11px]">
                    {isPlayingAudio ? '00:12' : '00:00'} / {meeting.durationFormatted}
                  </span>
                </div>

                <div className="flex items-center gap-1.5">
                  <button
                    onClick={() => setPlaybackSpeed(playbackSpeed === '1x' ? '1.5x' : playbackSpeed === '1.5x' ? '2x' : '1x')}
                    className="px-2 py-0.5 rounded-lg bg-slate-900 border border-slate-700 text-[10px] text-slate-300"
                  >
                    {playbackSpeed} ⌵
                  </button>
                </div>
              </div>
            </div>

            {/* Quick Link to Verbatim Transcript */}
            <button
              onClick={onOpenTranscript}
              className="w-full py-2.5 px-4 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-xs font-semibold text-cyan-400 flex items-center justify-center gap-1.5 transition"
            >
              <span>View Full Verbatim Transcript</span>
              <span>→</span>
            </button>
          </div>
        </div>

        {/* ✦ Ask Arohi Assistant Card with Suggestions (Screen 6 Bottom) */}
        <div className="p-4 rounded-2xl bg-gradient-to-r from-indigo-950/50 via-[#0c1224] to-purple-950/40 border border-cyan-500/30 mb-4">
          <div className="flex items-center gap-3 mb-3">
            <ArohiMeetAvatar size="sm" status="ready" />
            <div>
              <h3 className="text-xs font-bold text-white flex items-center gap-1">
                <span>✦ Ask Arohi</span>
              </h3>
              <p className="text-[11px] text-slate-400">
                Ask anything about decisions, numbers, objections, or assignments from this meeting.
              </p>
            </div>
          </div>

          {/* Quick Suggestion Chips */}
          <div className="flex flex-wrap gap-2 mb-3">
            {[
              'What were the key decisions?',
              'Show pending action items',
              'Who proposed the budget?',
              'Summarize in 1 minute'
            ].map((chip) => (
              <button
                key={chip}
                onClick={() => onOpenAskArohi(chip)}
                className="px-3 py-1 rounded-full bg-slate-900 hover:bg-cyan-500/20 border border-slate-700 hover:border-cyan-500/50 text-[11px] text-slate-300 transition"
              >
                {chip} ›
              </button>
            ))}
          </div>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (askArohiInput.trim()) {
                onOpenAskArohi(askArohiInput.trim());
                setAskArohiInput('');
              }
            }}
            className="flex gap-2"
          >
            <input
              type="text"
              value={askArohiInput}
              onChange={(e) => setAskArohiInput(e.target.value)}
              placeholder="Ask anything about this meeting..."
              className="flex-1 px-4 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400"
            />
            <button
              type="submit"
              className="px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-bold text-xs"
            >
              <Send className="w-3.5 h-3.5" />
            </button>
          </form>
        </div>
      </div>

      {/* Footer Branding */}
      <div className="w-full py-4 text-center border-t border-slate-800/80 bg-[#050811]/90">
        <p className="text-xs text-slate-400">
          <span className="font-serif italic text-purple-300">Meetings that matter.</span> • Arohi Meet / A Smarter Tomorrow
        </p>
      </div>
    </div>
  );
};

export default MeetPostMeetingView;
